fix: fix CI on master due to sdk path change (#123)
## Summary

emergency fix for the CI failures in master:

```
make[1]: Entering directory '/home/runner/work/magicblock-validator/magicblock-validator/magicblock-validator/test-programs'
cargo run --bin run-schedule-commit-tests
error: failed to load manifest for workspace member `/home/runner/work/magicblock-validator/magicblock-validator/magicblock-validator/test-programs/schedulecommit/program`
referenced by workspace at `/home/runner/work/magicblock-validator/magicblock-validator/magicblock-validator/test-programs/Cargo.toml`

Caused by:
  failed to load manifest for dependency `delegation-program-sdk`

Caused by:
  failed to read `/home/runner/work/magicblock-validator/magicblock-validator/delegation-program/sdk/Cargo.toml`
```